config/routes.rb
Rails.application.routes.draw do
  get 'pictures/index'

  get 'pictures/new'

  get 'pictures/create'

  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  get '/services', to: 'main#services'

  get '/contacts', to: 'main#contacts'

  root 'main#index'

  resources :users
  resources :pictures

  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  mount_uploader :picture, ImageUploader

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 6 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :require_login

  private
  def not_authenticated
    redirect_to root_path
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  skip_before_filter :require_login
  def index
  end

  def services
  end

  def contacts
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def index
    @pictures = Picture.all
  end

  def create
    params[:picture]['picture'].each do |a|
      Picture.create(picture: a)
    end
    redirect_to root_path
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_to root_path, notice: 'Вы успешно вошли'
    else
      flash.now[:alert] = 'Ошибка входа'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: 'Выход выполнен!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, only: [:new, :create]


  def index
    
  end


  def new
    if current_user
      redirect_to root_path
    else
      @user = User.new

    end
  end

  def show
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, notice: 'Вы успешно зарегистрировались'
    else
      render action:  'new'
    end
  end



  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, pictures_attributes: [:picture])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
head
  title Ilya
  = stylesheet_link_tag    'application'
  = javascript_include_tag 'application'
  = csrf_meta_tags


body
  nav.top-menu
    .nav-wrapper
      a href="#" class="brand-logo" МИР
      ul#nav-mobile.right.side-nav
        li
          = link_to 'Главная', root_path, class: 'waves-effect waves-light'
        li
          = link_to 'Услуги', services_path, class: 'waves-effect waves-light'
        li
          = link_to 'Портфолио', pictures_path, class: 'waves-effect waves-light'
        li
          = link_to 'Контакты', contacts_path, class: 'waves-effect waves-light'
        - if current_user
          li
            = link_to 'Панель управления', users_path, class: 'waves-effect waves-light'
          li
            = link_to 'Выйти', logout_path, method: :post, class: 'waves-effect waves-light'
      a(class="button-collapse" href="#" data-activates="nav-mobile")
        i class="mdi-navigation-menu"

  = flash[:notice]
  = flash[:alert]

  = yield

app/views/main/contacts.html.slim
h1 Main#contacts
p Find me in app/views/main/contacts.html.slim

app/views/main/index.html.slim
h1 Main#index
p Find me in app/views/main/index.html.slim

app/views/main/services.html.slim
h1 Main#services
p Find me in app/views/main/services.html.slim

app/views/pictures/index.html.slim
- @pictures.each do |picture|
  = image_tag(picture.picture)

app/views/user_sessions/new.html.slim
.container
  .row
    .col.m6.offset-m3
      h3 Вход
      = form_tag user_sessions_path, method: :post do
        = text_field_tag :email
        br
        = password_field_tag :password
        br
        = button_tag 'Войти', type: 'submit', class: 'waves-effect waves-light btn'

app/views/users/index.html.slim
h1 Панель управления
= link_to 'Выйти', logout_path, method: :post

= form_for :picture, url: pictures_path, html: { multipart: true } do |f|
  = f.fields_for :picture do |p|
    = p.file_field :picture, multiple: true, name: 'picture[picture][]'
    = p.hidden_field :picture_cache, multiple: true, name: 'picture[picture][]'
  = f.submit

app/views/users/new.html.slim
.container
  .row
    .col.m6.offset-m3
      h3 Регистрация
      = form_for @user do |f|
        = f.email_field :email, placeholder: 'Введите email'
        br
        = f.password_field :password, placeholder: 'Введите Пароль'
        br
        = f.password_field :password_confirmation, placeholder: 'Введите пароль еще раз'
        br
        = f.button 'Зарегистрироваться', type: 'submit', class: 'waves-effect waves-light btn'